apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: <Roadie>
  title: Sample Service # optional, human readable component name
  description: My first Backstage catalog item.
  annotations:
    github.com/project-slug: <Chandra_Costco Wholesale>/<Roadie>
spec:
  type: service
  owner: user:<chan7762>
  lifecycle: experimental
